library("GenomicFeatures")
library("GenomicAlignments")
library(rtracklayer)
library('LSD')
library("DESeq2")
library("genefilter")
library("gplots")
library("RColorBrewer")
library("AnnotationDbi")
library("org.Hs.eg.db")
library("Rsamtools")
library(Hmisc)
library("ggplot2")
library(reshape2)
library("scales")
library("gam")
library(pheatmap)
library(quantreg)
library("MASS")
library("Biostrings")
library("seqinr")
library("graphics")
library('data.table')
library("mgsa")
library("boot")
library("limma")
library(plyr)
library(gplots)
library(DAAG)
library(coefplot)
library("gplots")
library('stringr')
library("bootstrap")
library(glmnet)
library(pls)
library(caret)
library(multcomp)
library(pracma)
library(doParallel)
library(foreach)
library("broom")
library("tidyr")
#library("SciencesPo")
library(forcats)
library(pbapply)
library(pbmcapply)
library(pROC)
#library(multtest)
library(combinat)
library(formattable)
require(gridExtra)
library(gdata)
library("plotly")
library("plot3D")
library(rgl)
library(ggpval)
library("hydroGOF")
library("grid")
library("ggseqlogo")
library(cowplot)
library("svd")
library("dplyr")
library("stabs")
library("lars")
library(nlme)
library(metap)
library(ggrepel)
library(reticulate)
library("blockcluster")
library("UpSetR")
library(MOFAtools)
library("ggpubr")
library("vegan")
library("ggNT")
library("lmodel2")

source("./Utilities/DAVID_query.R")
source("./Utilities/add_pval_ggplot.R")
source("./Utilities/Utilities.R")
source("./Utilities/PlottingFunctions.R")


use_python("/Users/basak/anaconda3/bin/python/", required=TRUE)

options(java.parameters = "- Xmx4096m")
options(stringsAsFactors = FALSE)


#library(XLConnect)	# read Excel files

ourTheme <- theme(text = element_text(family = fontFamily), 
                  axis.title.x=element_text(family = fontFamily, size=7, face = "plain"), 
                  axis.title.y=element_text(family = fontFamily, size=7, face = "plain"),
                  axis.text.x=element_text(family = fontFamily, size=7),
                  axis.text.y=element_text(family = fontFamily, size=7),
                  plot.title = element_text(family = fontFamily, size=7, hjust = 0.5),
                  strip.text.x = element_text(size = 8, colour = "black"),
                  legend.text = element_text(family = fontFamily, size=7),
                  legend.title = element_text(family = fontFamily, size=10))

theme_set(theme_get() + theme_pubclean() + ourTheme)
